version: "3.8"
services:
  backend:
    build:
      context: ./backend
    image: queen-drones-backend:latest
    ports:
      - "5001:5000" 
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL_BUILD: "http://localhost:5001" 
    image: queen-drones-frontend:latest
    environment:
      REACT_APP_API_URL: "http://backend:5001" 
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 