version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000" # Map
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL_BUILD: "http://localhost:5001" # Backend URL during build
    environment:
      REACT_APP_API_URL: "http://backend:5001" # Backend URL during runtime
    ports:
      - "3000:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge




